apiVersion: v1

kind: Pod

metadata:
  name: ngnix-pod
  labels:
    app: ngnixapp

spec:
  containers:
    - name: ngnix-container
      image: ngnix

# To create it run the command: kubectl create -f 1_ngnix_pod_using_yaml.yml